# Generated by Django 4.2 on 2024-10-09 13:47

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=work.models.PortfolioItem.get_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
