# Generated by Django 4.2 on 2024-10-09 14:36

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=work.models.PortfolioItem.get_path),
        ),
    ]
