# Generated by Django 4.2 on 2024-10-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_portfolioitem_exerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
