# Generated by Django 4.2 on 2024-10-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_portfolioitem_github_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='description',
            new_name='description_one',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_teo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
