# Generated by Django 4.2 on 2024-10-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='branding',
            new_name='project_info',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='business_info',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='leads',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='usp',
        ),
    ]
