# Generated by Django 4.2 on 2024-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('exerpt', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('author_title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('main_img', models.ImageField(upload_to='blog/photos/%Y/%m/%d/')),
                ('lead_paragraph', models.TextField()),
                ('first_content', models.TextField()),
                ('subtitle_one', models.CharField(max_length=200)),
                ('second_content', models.TextField()),
                ('subtitle_two', models.CharField(max_length=200)),
                ('body_img', models.ImageField(upload_to='blog/photos/%Y/%m/%d/')),
                ('third_content', models.TextField()),
                ('thumb_img', models.ImageField(upload_to='blog/photos/%Y/%m/%d/')),
                ('body_img_two', models.ImageField(upload_to='blog/photos/%Y/%m/%d/')),
            ],
        ),
    ]
