# Generated by Django 4.2 on 2024-09-27 12:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_img',
            field=models.ImageField(upload_to=blog.models.Blog.get_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_img_two',
            field=models.ImageField(upload_to=blog.models.Blog.get_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_img',
            field=models.ImageField(upload_to=blog.models.Blog.get_path),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumb_img',
            field=models.ImageField(upload_to=blog.models.Blog.get_path),
        ),
    ]
