# Generated by Django 4.2 on 2024-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_body_img_alter_blog_body_img_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
