# Generated by Django 4.2 on 2024-10-22 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='second_content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='first_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
